# Generated by Django 3.2.12 on 2022-03-02 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='availabel',
            new_name='available',
        ),
    ]
